source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, '6.0'

pod 'Reachability', '~>3.0.0'
pod 'Masonry', '~> 0.6.3'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'WZLBadge', '~> 1.2.1'
